apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gatekeeper.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gatekeeper.labels" . | nindent 4 }}
data:
  config.yaml: |
  {{- toYaml .Values.config.yaml | nindent 4 }}
