apiVersion: v1
kind: Service
metadata:
  name: {{ include "transmission.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
{{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "transmission.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "transmission.fullname" . }}-tcp
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
{{- with .Values.service.peer.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.peer.type }}
  loadBalancerIP: {{ .Values.service.peer.loadBalancerIP }}
  ports:
    - port: {{ .Values.service.peer.port }}
      targetPort: {{ .Values.service.peer.port }}
      protocol: TCP
      name: tcp-peer
  selector:
    {{- include "transmission.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "transmission.fullname" . }}-udp
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
{{- with .Values.service.peer.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.peer.type }}
  loadBalancerIP: {{ .Values.service.peer.loadBalancerIP }}
  ports:
    - port: {{ .Values.service.peer.port }}
      targetPort: {{ .Values.service.peer.port }}
      protocol: UDP
      name: udp-peer
  selector:
    {{- include "transmission.selectorLabels" . | nindent 4 }}
