replicaCount: 3
nfs:
  server: ""
  path: ""
  mountOptions:
  - tcp
  - nfsvers=4
  - rw
  - port=2049
storageClass:
  defaultClass: true
resources:
  requests:
   cpu: 50m
   memory: 75Mi
  limits:
   cpu: 75m
   memory: 75Mi
