apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gatekeeper.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gatekeeper.labels" . | nindent 4 }}
data:
  CLIENT_ID: {{ .Values.config.clientID | b64enc | quote }}
  CLIENT_SECRET: {{ .Values.config.clientSecret | b64enc | quote }}
  ENCRYPTION_KEY: {{ .Values.config.encryptionKey | b64enc | quote }}
