{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "playground.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "playground.labels" . | nindent 4 }}
{{- end -}}
