---

apiVersion: v1
kind: Namespace
metadata:
  name: certificates

---

apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: certificates
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: contact@hugocortes.dev
    privateKeySecretRef:
      name: letsencrypt-staging
    http01: {}

---

apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: certificates
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: contact@hugocortes.dev
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssl
  namespace: certificates
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 0
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 10m
            memory: 10Mi

---

apiVersion: v1
kind: Service
metadata:
  name: ssl
  namespace: certificates
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    protocol: TCP
