kind: ConfigMap
apiVersion: v1
metadata:
  name: me
  namespace: hugocortes
  labels:
    app: me
    role: frontend
    env: local
data:
  BASE_URL: 'http://192.168.99.100:31100'
  APPEND_PORT: 'false'
  PORT: '1313'
