apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "calibre-web.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "calibre-web.labels" . | nindent 4 }}
spec:
  replicas: 1 # sqlite requires lock mounting
  selector:
    matchLabels:
      {{- include "calibre-web.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "calibre-web.fullname" . }}
  template:
    metadata:
      labels:
        {{- include "calibre-web.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "calibre-web.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: USE_CONFIG_DIR
              value: "false"
            - name: SET_CONTAINER_TIMEZONE
              value: "true"
            - name: CONTAINER_TIMEZONE
              value: {{ .Values.config.timezone }}
          volumeMounts:
            - name: config
              mountPath: /calibre-web/app
            - name: library
              mountPath: /books
          ports:
            - name: http
              containerPort: 8083
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 180
            periodSeconds: 5
            tcpSocket:
              port: http
          readinessProbe:
            initialDelaySeconds: 15
            periodSeconds: 5
            tcpSocket:
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
        - name: library
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingLibraryClaim }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
