apiVersion: v1
appVersion: 1.0.0
description: resume
name: me
version: 1.0.0
home: https://resume.hugocortes.me
sources:
- https://github.com/hugocortes/me
maintainers:
- name: hugocortes
  email: contact@hugocortes.me
