apiVersion: v1
appVersion: "1.0"
description: Resume static site.
name: me
version: 0.1.0
home: https://hugocortes.dev
sources:
- https://github.com/hugocortes/me
maintainers:
- name: Hugo Cortes
  email: contact@hugocortes.dev
