# Default values for me.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: hugocortes/me
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik-hugocortes
    traefik.frontend.rule.type: PathPrefix
  path: /
  hosts:
    - hugocortes.dev
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
   cpu: 0.025
   memory: 128Mi
  requests:
   cpu: 0.01
   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
