apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "miniflux.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "miniflux.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "miniflux.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "miniflux.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "miniflux.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: RUN_MIGRATIONS
              value: "1"
            - name: CREATE_ADMIN
              value: {{ ternary "1" "0" .Values.admin.create | quote }}
            - name: ADMIN_USERNAME
              value: {{ .Values.admin.user }}
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "miniflux.fullname" . }}
                  key: admin-password
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "miniflux.fullname" . }}
                  key: db-uri
            - name: OAUTH2_PROVIDER
              value: {{ .Values.oidc.provider }}
            - name: OAUTH2_CLIENT_ID
              value: {{ .Values.oidc.clientId }}
            - name: OAUTH2_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "miniflux.fullname" . }}
                  key: oauth2-client-secret
            - name: OAUTH2_REDIRECT_URL
              value: {{ .Values.oidc.redirectUrl }}
            - name: OAUTH2_OIDC_DISCOVERY_ENDPOINT
              value: {{ .Values.oidc.discoveryEndpoint }}
            - name: OAUTH2_USER_CREATION
              value: {{ .Values.oidc.userCreation | quote }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 5
            tcpSocket:
              port: http
          readinessProbe:
            initialDelaySeconds: 15
            periodSeconds: 5
            tcpSocket:
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
