apiVersion: v1
kind: Secret
metadata:
  name: {{ include "miniflux.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "miniflux.labels" . | nindent 4 }}
type: Opaque
data:
  db-uri: {{ printf "postgres://%s:%s@%s:%s/%s?sslmode=disable" .Values.database.user .Values.database.password .Values.database.host ( .Values.database.port | toString ) .Values.database.database | b64enc }}
  admin-password: {{ .Values.admin.password | b64enc }}
  oauth2-client-secret: {{ .Values.oidc.clientSecret | b64enc }}
