apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: spinnaker
  namespace: spinnaker
  labels:
    traffic-type: internal
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefix
spec:
  rules:
  - host: spinnaker.internal.hugocortes.me
    http:
      paths:
      - backend:
          serviceName: spin-deck
          servicePort: 9000
