{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "radarr.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "radarr.labels" . | nindent 4 }}
{{- end -}}
