# Default values for readarr.

image:
  repository: hotio/readarr
  pullPolicy: IfNotPresent
  tag: nightly-0.1.0.776

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

service:
  type: ClusterIP
  port: 8787

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  existingClaim: test
  existingDownloadsClaim: ""
  existingEBooksClaim: ""

config:
  puid: "911"
  pgid: "911"

env: []
  # - name: TZ
  #   value: America/Los_Angeles

nfs:
  syncInterval: "890"
  resources: {}
    # limits:
    #   cpu: 50m
    #   memory: 75Mi
    # requests:
    #   cpu: 50m
    #   memory: 75Mi
