# Default values for radarr.

image:
  repository: linuxserver/radarr
  pullPolicy: IfNotPresent
  tag: latest

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

service:
  type: ClusterIP
  port: 7878

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  existingClaim: ""
  existingDownloadsClaim: ""
  existingMoviesClaim: ""

config:
  puid: "911"
  pgid: "911"

env: []
  # - name: TZ
  #   value: America/Los_Angeles

sidecar:
  syncInterval: "890"
  resources: {}
    # limits:
    #   cpu: 50m
    #   memory: 75Mi
    # requests:
    #   cpu: 50m
    #   memory: 75Mi
