bases:
- ./../../base
patches:
- ./../configMap.yaml
- deployment.yaml
resources:
- ./../ingress.yaml
- ./../service.yaml
commonLabels:
  env: prod
  arch: arm32v6
imageTags:
- name: docker.io/hugocortes/paprika-api-js
  newTag: arm32v6
