---

apiVersion: v1
kind: Namespace
metadata:
  name: storage
  labels:
    istio-injection: enabled

---

apiVersion: v1
kind: Namespace
metadata:
  name: spin-system
  labels:
    istio-injection: enabled
