---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis
spec:
  storageClassName: standard
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  mountOptions:
  - tcp
  - nfsvers=4
  nfs:
    server: freenas.internal.corteshq.net
    path: /mnt/storage/ds0/p0/databases/redis

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
  namespace: storage
spec:
  storageClassName: standard
  volumeName: redis
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
