{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "me.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "me.labels" . | nindent 4 }}
{{- end -}}
