apiVersion: v1
kind: Service
metadata:
  name: {{ include "tautulli.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tautulli.labels" . | nindent 4 }}
{{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "tautulli.selectorLabels" . | nindent 4 }}
