apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "tautulli.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tautulli.labels" . | nindent 4 }}
spec:
  replicas: 1 # sqlite requires lock mounting
  selector:
    matchLabels:
      {{- include "tautulli.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "tautulli.fullname" . }}
  template:
    metadata:
      labels:
        {{- include "tautulli.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- if .Values.config.timezone }}
            - name: TZ
              value: {{ .Values.config.timezone }}
          {{- end }}
          volumeMounts:
            - name: conf
              mountPath: /config
            - name: plex-logs
              mountPath: /tautulli_logs
              readOnly: true
          ports:
            - name: http
              containerPort: 8181
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 120
            periodSeconds: 15
            failureThreshold: 4
            httpGet:
              path: /
              port: http
          readinessProbe:
            initialDelaySeconds: 120
            periodSeconds: 10
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: conf
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
        - name: plex-logs
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingPlexLogsClaim }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
