apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ynab-metrics.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ynab-metrics.labels" . | nindent 4 }}
data:
  config.json: {{ tpl (.Files.Get "files/config.json") . | toString | b64enc }}
