apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-nfs-nfs-server-provisioner-0
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /srv/volumes/data-nfs-nfs-server-provisioner-0
  claimRef:
    namespace: default
    name: data-nfs-nfs-server-provisioner-0
