# Declare variables to be passed into your templates.

replicaCount: 1

# imagePullSecrets:

image:
  repository: quay.io/kubernetes_incubator/nfs-provisioner
  tag: v1.0.9
  pullPolicy: IfNotPresent

service:
  type: ClusterIP

  nfsPort: 2049
  mountdPort: 20048
  rpcbindPort: 51413
  # nfsNodePort:
  # mountdNodePort:
  # rpcbindNodePort:

  externalIPs: []

persistence:
  enabled: true
  storageClass: "-"
  size: 50Gi

storageClass:
  create: true
  defaultClass: true
  name: nfs

rbac:
  create: true
  serviceAccountName: default

resources: {}

nodeSelector:
  kubernetes.io/hostname: k8s-slave-1

tolerations: []

affinity: {}
