replicaCount: 1

image:
  repository: idobry/chartmuseumui
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 3000

resources:
  requests:
   cpu: 125m
   memory: 128Mi
  limits:
   cpu: 250m
   memory: 256Mi

chartMuseum: chartmuseum.default.svc.cluster.local:8080
# basicJSON: [{\"username\":\"$CM_USER\",\"password\":\"$CM_PASS\"}]
