# Default values for tautulli.

replicaCount: 1

image:
  repository: tautulli/tautulli
  pullPolicy: IfNotPresent
  tag: latest

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

service:
  port: 8181
  type: ClusterIP

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  existingClaim: ""
  existingPlexLogsClaim: ""

config:
  timezone: America/Los_Angeles
