# Source:
# https://raw.githubusercontent.com/solo-io/squash/master/contrib/kubernetes/squash-client.yml
# Adds nodeSelector for mixed arch k8s cluster

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: squash-client
  name: squash-client
  namespace: squash
spec:
  template:
    metadata:
      labels:
        app: squash-client
    spec:
      # For mixed arch k8s cluster
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      hostPID: true
      containers:
      - name: squash-client
        image: soloio/squash-client:v0.3.1
        volumeMounts:
        - mountPath: /var/run/cri.sock
          name: crisock
        securityContext:
          privileged: true
        ports:
        - containerPort: 1234
          protocol: TCP
        env:
        - name: SERVERURL
          value: "http://$(SQUASH_SERVER_SERVICE_HOST):$(SQUASH_SERVER_SERVICE_PORT_HTTP_SQUASH_API)"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: HOST_ADDR
          value: "$(POD_NAME).$(POD_NAMESPACE)"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      volumes:
      - name: crisock
        hostPath:
          path: /var/run/dockershim.sock
