apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-external
  namespace: kube-system
data:
  traefik.toml: |
    defaultEntryPoints = ["http","https"]
    debug = false
    logLevel = "INFO"

    # Do not verify backend certificates (use https backends)
    InsecureSkipVerify = true

    [entryPoints]
      [entryPoints.http]
        address = ":80"
        compress = true
      [entryPoints.https]
        address = ":443"
          [entryPoints.https.tls]

    [ping]
      entryPoint = "http"

    [kubernetes]
      # Only create ingresses where the object has traffic-type: external label
      labelselector = "traffic-type=external"
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: traefik-external
  namespace: kube-system
  labels:
    k8s-app: traefik-external
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik-external
  template:
    metadata:
      labels:
        k8s-app: traefik-external
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik
        name: traefik-external
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: admin
          containerPort: 8080
        args:
        - --api
        - --configfile=/config/traefik.toml
        livenessProbe:
          httpGet:
            path: /ping
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /config
          name: traefik-external
      volumes:
      - name: traefik-external
        configMap:
          name: traefik-external
---
kind: Service
apiVersion: v1
metadata:
  name: traefik-external
  namespace: kube-system
  labels:
    k8s-app: traefik-external
spec:
  selector:
    k8s-app: traefik-external
  externalTrafficPolicy: Local
  ports:
    - protocol: TCP
      port: 80
      name: web
    - protocol: TCP
      port: 443
      name: https
    - protocol: TCP
      port: 8080
      name: admin
  type: LoadBalancer
  loadBalancerIP: 192.168.2.100
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-external
  namespace: kube-system
  labels:
    traffic-type: internal
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefix
spec:
  rules:
  - host: traefik-ext.internal.hugocortes.me
    http:
      paths:
      - backend:
          serviceName: traefik-external
          servicePort: admin
