# Default values for plex.

image:
  repository: plexinc/pms-docker
  pullPolicy: IfNotPresent
  tag: plexpass

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

service:
  type: ClusterIP
  loadBalancerIP: ""
  port:
    pms: 32400
    pds: 32469
    pc: 3005
    pcr: 8324

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  existingClaim: ""
  existingMoviesClaim: ""
  existingTVClaim: ""
  existingTranscodeClaim: ""

config:
  transcodeOnHost: false
  timezone: America/Los_Angeles

env: []
  # - name: CHANGE_CONFIG_DIR_OWNERSHIP
  #   value: "false"
  # - name: ADVERTISE_IP
  #   value: "http://:32400/"

tautulli:
  enabled: false
  image:
    repository: tautulli/tautulli
    pullPolicy: IfNotPresent
    tag: latest
  service:
    port: 8181
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
