apiVersion: v1
kind: Service
metadata:
  name: {{ include "plex.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "plex.labels" . | nindent 4 }}
spec:
  externalTrafficPolicy: Local
  type: {{ .Values.service.type }}
{{- if eq .Values.service.type "LoadBalancer" }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
  ports:
    - port: {{ .Values.service.port.pms }}
      targetPort: media-server
      protocol: TCP
      name: media-server
    - port: {{ .Values.service.port.pc }}
      targetPort: companion
      protocol: TCP
      name: companion
    - port: {{ .Values.service.port.pcr }}
      targetPort: companion-roku
      protocol: TCP
      name: companion-roku
    - port: {{ .Values.service.port.pds }}
      targetPort: dlna-server
      protocol: TCP
      name: dlna-server
  {{- if .Values.tautulli.enabled }}
    - port: {{ .Values.tautulli.service.port }}
      targetPort: tautulli
      protocol: TCP
      name: tautulli
  {{- end }}
  selector:
    {{- include "plex.selectorLabels" . | nindent 4 }}
