apiVersion: v1
kind: Service
metadata:
  name: {{ include "blue-green.fullname" . }}
  namespace: {{ .Release.Namespace}}
  labels:
    app: {{ include "blue-green.name" . }}
    chart: {{ include "blue-green.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "blue-green.name" . }}
    release: {{ .Release.Name }}
