apiVersion: v1
kind: Service
metadata:
  name: {{ include "me.fullname" . }}
  namespace: {{ .Release.Namespace}}
  labels:
    app.kubernetes.io/name: {{ include "me.name" . }}
    helm.sh/chart: {{ include "me.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "me.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
