apiVersion: v1
appVersion: "1.0"
description: Blue Green deployment example. 
name: blue-green
version: 0.1.0
home: https://blue-green.hugocortes.dev
sources:
- https://github.com/hugocortes/blue-green
maintainers:
- name: Hugo Cortes
  email: contact@hugocortes.dev
