apiVersion: v1
kind: Service
metadata:
  name: konga-gui
spec:
  type: LoadBalancer
  ports:
  - name: konga-gui
    port: 80
    targetPort: 1337
    protocol: TCP
  selector:
    app: konga

---
apiVersion: v1
kind: Pod
metadata:
  name: konga-rc
  labels:
    app: konga
spec:
  containers:
    - name: konga-rc
      image: pantsel/konga:latest
      ports:
        - containerPort: 1337

