apiVersion: v1
kind: Service
metadata:
  name: konga-gui
spec:
  type: LoadBalancer
  ports:
  - name: konga-gui
    port: 80
    targetPort: 1337
    protocol: TCP
  selector:
    app: konga

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: konga-rc
  labels:
    app: konga
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: konga
    spec:
      containers:
        - name: konga-rc
          image: pantsel/konga:latest
          ports:
            - containerPort: 80

