kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: paprika-api-js
  namespace: hugocortes
  labels:
    app: paprika-api-js
    role: backend
    env: local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paprika-api-js
      role: backend
      env: local
  template:
    metadata:
      name: paprika-api-js
      labels:
        app: paprika-api-js
        role: backend
        env: local
    spec:
      containers:
      - name: paprika-api-js
        image: docker.io/hugocortes/paprika-api-js
        resources:
          limits:
            cpu: 200m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        ports:
          - name: http
            containerPort: 3000
        livenessProbe:
          httpGet:
            path: /status
            port: http
          initialDelaySeconds: 3
          periodSeconds: 3
          timeoutSeconds: 1
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: paprika-api-js
              key: PORT
        - name: HOST
          valueFrom:
            configMapKeyRef:
              name: paprika-api-js
              key: HOST
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: paprika-api-js
              key: LOG_LEVEL
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: paprika-api-js
              key: NODE_ENV
