apiVersion: v1
kind: Service
metadata:
  name: {{ include "transmission.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "transmission.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "transmission.fullname" . }}-peer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
spec:
  type: {{ .Values.peer.type }}
  {{- if .Values.peer.loadBalancerIP }}
  loadBalancerIP: {{ .Values.peer.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.peer.port }}
      targetPort: {{ .Values.peer.port }}
      protocol: TCP
      name: peer
  selector:
    {{- include "transmission.selectorLabels" . | nindent 4 }}
