apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chartmuseumui.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chartmuseumui.labels" . | nindent 4 }}
data:
  CHART_MUSESUM_URL: {{ .Values.chartMuseum }}
