apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "calibre-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "calibre-server.labels" . | nindent 4 }}
spec:
  replicas: 1 # prevent db file overwrites...
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "calibre-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "calibre-server.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "calibre-server.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TZ
              value: {{ .Values.config.timezone }}
            - name: PUID
              value: {{ .Values.config.puid | quote }}
            - name: PGID
              value: {{ .Values.config.pgid | quote }}
            # must create a user to allow basic auth to work
            - name: CLI_ARGS
              value: –auth-mode=basic
          volumeMounts:
            - name: config
              mountPath: /config
              subPath: server
            - name: library
              mountPath: /books
          ports:
            - name: http-server
              containerPort: 8080
              protocol: TCP
            - name: http-sharing
              containerPort: 8081
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
        - name: library
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingLibraryClaim }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
