apiVersion: v1
kind: Service
metadata:
  name: {{ include "calibre-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "calibre-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.server.port }}
      targetPort: http-server
      protocol: TCP
      name: http-server
    - port: {{ .Values.service.sharing.port }}
      targetPort: http-sharing
      protocol: TCP
      name: http-sharing
  selector:
    {{- include "calibre-server.selectorLabels" . | nindent 4 }}
