apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "plex.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "plex.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "plex.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "plex.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          - name: conf
            mountPath: /config
          - name: movies
            mountPath: /data/movies
          - name: tv
            mountPath: /data/tv-shows
          - name: transcode
            mountPath: /transcode
          ports:
          - name: media-server
            containerPort: 32400
            protocol: TCP
          - name: dlna-server
            containerPort: 32469
            protocol: TCP 
          - name: companion
            containerPort: 3005
            protocol: TCP 
          - name: companion-roku
            containerPort: 8324
            protocol: TCP 
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            httpGet:
              path: /identity
              port: 32400
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            httpGet:
              path: /identity
              port: 32400
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: conf
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim }}
      - name: movies
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingMoviesClaim }}
      - name: tv
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingTVClaim }}
    {{- if .Values.config.transcodeOnHost }}
      - name: transcode
        hostPath:
          path: /tmp
    {{- else }}
      - name: transcode
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingTranscodeClaim }}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
