apiVersion: v1
kind: Service
metadata:
  name: {{ include "plex.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "plex.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.loadBalancerIP }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "plex.selectorLabels" . | nindent 4 }}
