kind: Service
apiVersion: v1
metadata:
  name: blue-green
  namespace: hugocortes
  labels:
    app: blue-green
    role: frontend
    env: local
spec:
  type: ClusterIP
  selector:
    app: blue-green
    role: frontend
    env: local
  ports:
  - name: http
    port: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: blue-green
  namespace: hugocortes
  labels:
    app: blue-green
    role: frontend
    env: local
    traffic-type: external
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefix
spec:
  rules:
  - host: blue-green.hugocortes.me
    http:
      paths:
      - backend:
          serviceName: blue-green
          servicePort: http
