apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: LoadBalancer
  ports:
  - name: api
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: api

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: docker.io/hugocortes/api:latest
          imagePullPolicy: Always
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: PORT
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: HOST
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: LOG_LEVEL
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: SECRET
